"""
STEP 3 — FastAPI wrapper around the RAG chatbot

Exposes 3 endpoints:
  GET  /health      → check if server is running and if PDF is loaded
  POST /upload      → upload a PDF file, builds the RAG chain
  POST /ask         → ask a question, get an answer

Run:
    python 3_fastapi_app.py

Then open browser: http://localhost:8000/docs
    → interactive UI to test all endpoints (auto-generated by FastAPI)

Or use curl:
    curl -X POST http://localhost:8000/upload -F "file=@yourfile.pdf"
    curl -X POST http://localhost:8000/ask -H "Content-Type: application/json" -d '{"question":"What is this document about?"}'
"""

import os
import shutil
import tempfile
from dotenv import load_dotenv

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel                                         # data validation

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.chains import RetrievalQA

load_dotenv()

# ─── FastAPI App ──────────────────────────────────────────────────────────────
app = FastAPI(
    title="RAG Chatbot API",
    description="Upload a PDF and ask questions about it",
    version="1.0.0",
)

# CORS — allows the React/HTML frontend to call this API from a browser
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      # in production, replace * with your frontend URL
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Global state ─────────────────────────────────────────────────────────────
# In a real app you'd use a database — for learning, a global variable is fine
rag_chain = None
loaded_filename = None


# ─── Request/Response models ──────────────────────────────────────────────────
# Pydantic models define the shape of JSON input/output
class QuestionRequest(BaseModel):
    question: str                   # the JSON must have a "question" field

class AnswerResponse(BaseModel):
    question: str
    answer: str
    sources: list[str]              # list of source chunk previews


# ─── Helper: build RAG chain from a PDF file path ─────────────────────────────
def build_rag_chain_from_file(file_path: str):
    # Load PDF
    loader = PyPDFLoader(file_path)
    pages  = loader.load()

    # Chunk
    splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks   = splitter.split_documents(pages)

    # Embed + store
    embeddings  = OpenAIEmbeddings()
    vectorstore = FAISS.from_documents(chunks, embeddings)

    # Build chain
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
    llm       = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
    chain     = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever,
        return_source_documents=True,
    )
    return chain, len(chunks)


# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
def health_check():
    """Check if the server is running and whether a PDF has been loaded."""
    return {
        "status": "ok",
        "pdf_loaded": rag_chain is not None,
        "loaded_file": loaded_filename,
    }


@app.post("/upload")
async def upload_pdf(file: UploadFile = File(...)):
    """
    Upload a PDF file. The server will parse it and build the RAG chain.
    Must be called before /ask.
    """
    global rag_chain, loaded_filename

    # Validate file type
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted")

    # Save to a temp file (FastAPI gives us a stream, not a path)
    tmp_path = None
    try:
        # tempfile.NamedTemporaryFile creates a temp file on disk
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            shutil.copyfileobj(file.file, tmp)   # copy upload stream → temp file
            tmp_path = tmp.name

        # Build the RAG chain
        chain, chunk_count = build_rag_chain_from_file(tmp_path)

        # Store in global state
        rag_chain       = chain
        loaded_filename = file.filename

        return {
            "message": f"PDF '{file.filename}' loaded successfully",
            "pages_loaded": "see chunk count",
            "chunks_created": chunk_count,
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process PDF: {str(e)}")

    finally:
        # Always delete the temp file
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)


@app.post("/ask", response_model=AnswerResponse)
async def ask_question(req: QuestionRequest):
    """
    Ask a question about the uploaded PDF.
    Returns the answer and the source chunks that were used.
    """
    if rag_chain is None:
        raise HTTPException(
            status_code=400,
            detail="No PDF loaded. Call POST /upload first."
        )

    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty")

    try:
        result = rag_chain.invoke({"query": req.question})

        # Extract source previews
        sources = []
        for doc in result.get("source_documents", []):
            page    = doc.metadata.get("page", "?")
            preview = doc.page_content[:150].replace("\n", " ")
            sources.append(f"Page {page}: {preview}...")

        return AnswerResponse(
            question=req.question,
            answer=result["result"],
            sources=sources,
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating answer: {str(e)}")


# ─── Run ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    print("\n  RAG API starting...")
    print("  Docs: http://localhost:8000/docs")
    print("  Health: http://localhost:8000/health\n")
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)
